//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paint.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap abajo {
            get {
                object obj = ResourceManager.GetObject("abajo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap abajos {
            get {
                object obj = ResourceManager.GetObject("abajos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del programa: Painter
        ///Creado: Junio de 2021
        ///Patentado: Junio 2021
        ///Creador, diseñador y programador:Lucas Da Silva Fradkin
        ///Nombre de la compañia: Dasilva Company
        ///Encargo a nombre de: Jose Pablo Rusca
        ///Motivo: Segundo parcial de la materia GUI 1.
        /// </summary>
        public static string acercaDe {
            get {
                return ResourceManager.GetString("acercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agradecimietno especial:
        ///
        ///Handicon: por el icon de la linea
        ///berkahicon: por el icono de la mano.
        /// </summary>
        public static string agradezco {
            get {
                return ResourceManager.GetString("agradezco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arriba {
            get {
                object obj = ResourceManager.GetObject("arriba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arribas {
            get {
                object obj = ResourceManager.GetObject("arribas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap binario {
            get {
                object obj = ResourceManager.GetObject("binario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap binario1 {
            get {
                object obj = ResourceManager.GetObject("binario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap binario2 {
            get {
                object obj = ResourceManager.GetObject("binario2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap deshacer {
            get {
                object obj = ResourceManager.GetObject("deshacer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dibujo {
            get {
                object obj = ResourceManager.GetObject("dibujo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hand__1_ {
            get {
                object obj = ResourceManager.GetObject("hand__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu editor:
        ///
        ///Tendras diferentes herramientas y sus respectivos atajos para usar durante tu proyecto.
        ///
        ///Deshacer: Eliminara la ultima figura de tu dibujo
        ///
        ///Recortar: Eliminara la figura seleccionada en la pestaña Listado
        ///
        ///Adelantar: Adelantara una posicion a la figura seleccionada.
        ///
        ///Atrasar: Atrasara una posicion a la figura seleccionada.
        ///
        ///Adelantar Al frente: Adelantara al frente la figura seleccionada.
        ///
        ///Atrasar Al fondo: Atrasara al fondo a la figura seleccionada. 
        ///
        ///AVISO: En las ultimas cua [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string infoDeMenuEditar {
            get {
                return ResourceManager.GetString("infoDeMenuEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Binevenido a Painter, en este mensaje le enseñare las cuestiones basicas del programa.
        ///
        ///Ventana Agregador: Es donde podra crear nuevos proyectos para dibujar, si la cierra se cerrara todo el programa
        ///
        ///Ventana Objeto: Es donde seleccionara que tipo de figura quiere dibujar, junto a su color y tamaño de trazo(el 
        ///tamaño de letra es pone al hacer click en el boton de texto),tambien debajo del boton de texto hay un 
        ///recuadro para que escriba el texto querido
        ///
        ///Ventana Lienzo: Es donde dibujara su proyect [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string InfoGeneral {
            get {
                return ResourceManager.GetString("InfoGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventana de edicion:
        ///
        ///Aqui podras editar las figuras ya dibujadas, podras editar distintas cosas segun el tipo de figura.
        ///
        ///Primer punto: Podras modificar las cordenadas X e Y de tu dibujo, este punto es la esquina superior izquierda
        ///y la unica figura que no tiene habilitado esta opcion es la figura a mano alzada que no se puede mover
        ///
        ///Segundo punto: Esta opcion esta solo disponible para la figura linea, es igual que primer punto pero relacionado con la otra punta de la linea
        ///
        ///Tamaño: Esta disponible [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string InfoVentanaEditor {
            get {
                return ResourceManager.GetString("InfoVentanaEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventana listado.
        ///
        ///En esta ventana apareceran todas las figuras dibujadas en el la pestaña Lienzo, cada vez que dibujes un item este sera autoseleccionado para aparecer en la ventana Editor donde podras editarlo.
        ///Si deseas mover o usar cualquiera de las otras herramientas del menu editar(exceptuando deshacer) deberas primero hacer click en el listado al objeto con el que desea tratar.
        ///
        ///AVISO: Se pueden mover todas las figuras excepto las creadas a mano alzada.
        ///AVISO: La figura linea puede ser movida pe [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string infoVentanaListado {
            get {
                return ResourceManager.GetString("infoVentanaListado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mano {
            get {
                object obj = ResourceManager.GetObject("mano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minus__1_ {
            get {
                object obj = ResourceManager.GetObject("minus__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tex {
            get {
                object obj = ResourceManager.GetObject("tex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tijera {
            get {
                object obj = ResourceManager.GetObject("tijera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
